# Generated by Django 5.0.14 on 2026-08-02 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Préstamo')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite de Devolución')),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Atrasado', 'Atrasado')], default='Activo', max_length=20, verbose_name='Estado del Préstamo')),
                ('comprobante_pdf', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante PDF')),
                ('codigo_verificacion', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Verificación')),
                ('dias_retraso', models.IntegerField(default=0, verbose_name='Días de Retraso')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='usuarios.lector', verbose_name='Lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='catalogo.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
