# Generated by Django 5.0.14 on 2026-08-02 16:26

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Portada (Imagen)')),
                ('muestra_pdf', models.FileField(blank=True, null=True, upload_to='muestras/', validators=[catalogo.models.validar_tamano_pdf], verbose_name='Muestra / Resumen PDF (Máx 8 MB)')),
                ('cantidad_total', models.PositiveIntegerField(default=1, verbose_name='Cantidad Total de Copias')),
                ('copias_disponibles', models.PositiveIntegerField(default=1, verbose_name='Copias Disponibles')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='catalogo.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
