# Generated by Django 5.0.14 on 2026-08-02 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_institucional', models.CharField(max_length=50, unique=True, verbose_name='Código Institucional')),
                ('tipo', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente')], default='Estudiante', max_length=20, verbose_name='Tipo de Lector')),
                ('foto_carne', models.ImageField(blank=True, null=True, upload_to='carnes/', verbose_name='Foto de Carné')),
                ('estado', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Sancionado', 'Sancionado')], default='Habilitado', max_length=20, verbose_name='Estado de Cuenta')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lector_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema')),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
